name: Postman Weather API Tests

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to the main branch

jobs:
  run-api-tests:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Install Newman
        run: npm install -g newman  

      - name: Run Postman Tests
        run: newman run Postman_Weather_Collection.json -e Postman_Weather_Environment.json
        
      - name: Run Postman Tests with Reports
        run: newman run Postman_Weather_Collection.json -e Postman_Weather_Environment.json --reporters cli,junit --reporter-junit-export results.xml
